{% set name = "svgwrite" %}
{% set version = "1.4" %}
{% set sha256 = "b38ac03b67f81c728d81a33e4711aaf3ab136a57156d721bb17f88525d9909bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyparsing >=2.0.1
  run:
    - python
    - pyparsing >=2.0.1

test:
  imports:
    - svgwrite

about:
  home: https://github.com/mozman/svgwrite
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: A Python library to create SVG drawings.
  description: A Python library to create SVG drawings.
  doc_url: http://svgwrite.readthedocs.io
  dev_url: https://github.com/mozman/svgwrite

extra:
  recipe-maintainers:
    - jeromekelleher
